# Site settings

title: Reg Tait, web designer in Hull, UK
email: xyz@regmtait.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Reg Tait is a web designer and developer based in Hull, East Yorkshire, who provides bespoke websites with content management systems alongside illustration and other one-man design agency services. Hand-crafted quality. Pure class.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.regmtait.co.uk"
twitter_username: regmtait

# Build settings

markdown: kramdown
permalink: /:year/:title/


sass:
  style: compressed

collections:
  projects:
    output: true
    permalink: /project/:path/
